namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_ALCHEMY_POLICY_ID_ETH_SEPOLIA: string
    NEXT_PUBLIC_ALCHEMY_URL_ETH_SEPOLIA: string
    NEXT_PUBLIC_ALCHEMY_KEY_ETH_SEPOLIA: string
    NEXT_PUBLIC_GA_ID: string
    MONGODB_URI: string
    THIRDWEB_AUTH_PRIVATE_KEY: string
    NEXT_PUBLIC_CALLSIGN: string
    NEXT_PUBLIC_TW_CLIENT_ID: string
    NEXT_PUBLIC_THIRDWEB_AUTH_DOMAIN: string
  }
}
